#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vi'
export VISUAL='vi'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
  export LC_ALL='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  ~/bin
  ~/.nodejs-packages/bin
  ~/.npm-packages/bin
  ~/.composer/vendor/bin
  ~/Library/Android/sdk/tools
  ~/Library/Android/sdk/platform-tools
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Set defaut Vagrant provider
export VAGRANT_DEFAULT_PROVIDER=parallels

# GO Path
export GOPATH=/Users/richard/Library/go

# Load Google Cloud Platform completions
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

# Don't add virtualenv name to prompt
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Setup NVM
export NVM_DIR="$HOME/.nvm"
source /usr/local/opt/nvm/nvm.sh

# Set GEM home
export GEM_HOME="$HOME/.gem"

# pyenv autoload virtualenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
